pipeline {
    agent any

    environment {
        SERVICE_NAME = "order-service"
    }

    stages {

        stage('Checkout') {
            steps {
                echo "Checkout order-service"
                checkout scm
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo "Running SonarQube - order-service"
                withSonarQubeEnv('SonarQube') {
                    sh """
                        ${tool 'SonarScanner'}/bin/sonar-scanner \
                        -Dsonar.projectKey=${SERVICE_NAME} \
                        -Dsonar.sources=${SERVICE_NAME}
                    """
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }

    post {
        always {
            echo "Cleaning up workspace for order-service"
            cleanWs()
        }
        success {
            echo "Order Service SUCCESS"
        }
        failure {
            echo "Order Service FAILED"
        }
    }
}