apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: cloudmart
  labels:
    app: user-service
spec:
  # ClusterIP: internal only — ALB routes to pods directly via target-type: ip
  # No more AWS LoadBalancer per service (saves cost)
  type: ClusterIP
  selector:
    app: user-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000