pipeline {
    agent any

    environment {
        SERVICE_NAME = "user-service"
    }

    stages {
        stage('Checkout SCM') {
            steps {
                checkout scm
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh """
                        ${tool 'SonarScanner'}/bin/sonar-scanner \
                        -Dsonar.projectKey=${SERVICE_NAME} \
                        -Dsonar.sources=${SERVICE_NAME} \
                        -Dsonar.language= python \
                        -Dsoanr.python.version=3.11 \
                    """
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
    }

    post {
        always {
            echo "Cleaning up workspace for order-service"
            cleanWs()
        }
        success {
            echo "User Service SUCCESS"
        }
        failure {
            echo "User Service FAILED"
        }
    }
}